home:
  path: /
  controller: App\Controller\HomeController:index

security_registration:
  path: /ajouter-utilisateur
  controller: App\Controller\SecurityController::registration

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

add_classroom:
  path: /ajouter-cours
  controller: App\Controller\ClassroomController::addClassroom

edit_classroom:
  path: /modifier-cours/{classroom_id}
  controller: App\Controller\ClassroomController::editClassroom

showqrcode:
  path: /cours/{classroom_id}
  controller: App\Controller\ClassroomController::showQrCode

qr_code_generate:
  path: /qr_code_url/{text}.{extension}
  requirements:
    text: "[\\w\\W]+"
  defaults:
    _controller: Endroid\QrCodeBundle\Controller\GenerateController

generate_token:
  path: /generate-token
  controller: App\Controller\ApiController::tokenGeneration

refresh_token:
  path: /refresh-token
  controller: App\Controller\ApiController::tokenRefresh

get_user_from_token:
  path: /get-user-from-token
  controller: App\Controller\ApiController::getUserFromToken

testapi:
  path: /api/testapi
  controller: App\Controller\ApiController::testApi