home:
  path: /
  controller: App\Controller\HomeController:index

security_registration:
  path: /ajouter-utilisateur
  controller: App\Controller\SecurityController::registration

security_login:
  path: /login
  controller: App\Controller\SecurityController::login

security_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

add_classroom:
  path: /ajouter-cours
  controller: App\Controller\ClassroomController::addClassroom

edit_classroom:
  path: /modifier-cours/{classroom_id}
  controller: App\Controller\ClassroomController::editClassroom

showqrcode:
  path: /cours/{classroom_id}
  controller: App\Controller\ClassroomController::showQrCode

qr_code_generate:
  path: /qr_code_url/{text}.{extension}
  requirements:
    text: "[\\w\\W]+"
  defaults:
    _controller: Endroid\QrCodeBundle\Controller\GenerateController

validate_manually:
  path: /cours/{classroom_id}/validation-manuelle
  controller: App\Controller\ClassroomController::validateManually